  (* Assume these modules are generated by ocamllex and ocamlyacc *)
  open Compiler
  module TigerParser = Grammar
  let typecheck filename =
    let ic = open_in filename in
      let lexbuf = Lexing.from_channel ic in
      let _ : Types.ty = TigerParser.program TigerLexer.token lexbuf |> Semant.transProgDebug in
      ()
(*    let typecheck filename = 
      let ic = open_in filename in
      let lexbuf = Lexing.from_channel ic in
      let result = Grammar.program TigerLexer.token lexbuf in
      Semant.transExp Env.base_venv Env.base_tenv result 
      *)
let isGood = ref true
let () = try Util.pass_cmd_arg typecheck with
| ErrorMsg.Error msg -> print_endline msg
let _ = if !isGood then
  print_endline "Successful!"